### PR TITLE
Update LSTM Models to integerized tessdata_best for files<25mb - 2nd set

### PR DESCRIPTION
**Pull request by Shreeshrii**
2nd set of files, there seems to be a limit to web upload.

### CODE REVIEW

**Comment by stweil** [comment]
As far as I see `chi_tra.traineddata` and `chi_sim.traineddata` are still old because the files are very large. Should I update them? Are more files to be done? What about the cube data? I‌ think it can be removed from five languages.

**Comment by Shreeshrii** [comment]
I was not able to upload large files.

So, yes, it will be useful to make all consistent and upload the others.

I can look up the list though I am sure you can figure it out faster based
on file size.

I had not deleted any cube related files. They can be deleted as cube is
not supported for 4.0.0. This can be done for all languages, not just the
large files.

Thanks.

**Comment by Shreeshrii** [comment]
Also, there was a recent request for script files for tessdata also.

There are no legacy models for scripts, but integer versions of best models could be provided for them.

**Comment by Shreeshrii** [comment]
>Should the version component also be updated by a copy from tessdata_best?

For script files that maybe ok. Though I do think that you should suffix to indicate conversion to integer.

Ray had pulled out more details from traineddata files which include whether it is integer model or not.

But unless that info is provided via combine_tessdata in an easy manner, we can include in version.

Otherwise there is no quick way to know whether a trainer data file is from best or fast or best_int.

It is possible that the version string got corrupted since I ran conversion a couple of times . Please fix as you see fit. Thanks.

**Pull request merged**
