### PR TITLE
Only int best model for indic and arabic script languages

### PR DESCRIPTION
**Pull request by Shreeshrii**
Remove legacy model as it is not accurate, use --oem 1 as default via config file.
Also takes care of file size problem for san, tel etc.

### CODE REVIEW

**Comment by amitdo** [comment]
I think that for fas the legacy files should be removed.

https://github.com/tesseract-ocr/tessdata/issues/3#issuecomment-121008628

https://groups.google.com/forum/?hl=en#!topic/tesseract-ocr/rdWBC-A7Pbs
https://groups.google.com/forum/?hl=en#!topic/tesseract-ocr/dUR0bSbYIYM

**Comment by Shreeshrii** [comment]
Probably also for Arabic.

**Comment by amitdo** [comment]
ara never had support for the regular (non-cube) legacy engine.

but there are other traineddata that use the Arabic script.

**Comment by Shreeshrii** [comment]
@zdenop  You can merge this now. Thanks!

**Comment by oda-gitso** [comment]
@Shreeshrii Could you please point me towards resources explaining why this decision was made?

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tessdoc/blob/bc73ab3c1ed7846a48ef2630a053017de3ec07c3/tess4/4.0-Accuracy-and-Performance.md

**Comment by oda-gitso** [comment]
@amitdo Thank you

**Pull request merged**
