### PR TITLE
update readme for integerized LSTM models

### PR DESCRIPTION
**Pull request by Shreeshrii**
Will upload the traineddata files next.

### CODE REVIEW

**Comment by amitdo** [comment]
>GitHub upload failed for files > 25mb

Which files?

**Comment by Shreeshrii** [comment]
I have created another PR with 2nd set of fles, please merge that too.

I will list the languages that could not be uploaded after that.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
So far, the files that did not upload are:

bod
chi_sim
chi_tra
jpn
kan
khm
lao
mya
san

The older version of files are still there.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by stweil** [comment]
@Shreeshrii, how did you handle `deu_frak.traineddata` and the other files which have no best traineddata?

**Comment by Shreeshrii** [comment]
@stweil I did not have a check whether file exists in best. Just the version string would have gotten updated.

**Comment by Shreeshrii** [comment]
@stweil 

Is it just the three user contributed files , dan_frak, deu_frak and slk_frak?
Is there a way to go back to an older commit only for these files (functionality is still the same, just the version string is changed) or should I reupload an older version?

**Comment by stweil** [comment]
No, I don't need that this is necessary. We can keep them as they are.

**Comment by amitdo** [comment]
kur has no lstm. Does it have Latin or Arabic letters?
kur_ara is from best.

**Comment by Shreeshrii** [comment]
I looked at langdata repo just now. It has both kur and kur_ara. Looks like there was a change in langcode but the files were not moved. 

I had taken the list of RTL languages from language_specific.sh, it did not have kur, but has kur_ara.

langdata/kur has training text, wordlists etc, in Arabic script. While langdata/kur_ara only has a list of desired and forbidden characters. Hence the kur_ara traineddata file in tessdata_best is not correct. Probably same will apply to tessdata_fast - I haven't checked.

I will file an issue in langdata mentioning this. Hopefully all this will be fixed when Ray/Jeff update langdata for 4.0.0.

**Comment by amitdo** [comment]
An older issue about kur: #45

**Pull request merged**
