### PR TITLE
Added fast LSTM+legacy model for Akkadian

### PR DESCRIPTION
**Pull request by wincentbalin**
For training documentation, see https://github.com/tesseract-ocr/tesstrain/wiki/Akkadian-Cuneiform

### CODE REVIEW

**Comment by zdenop** [comment]
[tesseract-ocr/tessdata](https://github.com/tesseract-ocr/tessdata) repository is for Google trained data. For custom trained data please use https://github.com/tesseract-ocr/tessdata_contrib

**Comment by stweil** [comment]
@zdenop, do you expect more trained data from Google? If not, I think that we could start adding new languages here as well as long as all required information (langdata / langdata_lstm, documentation) is provided, too.

**Comment by zdenop** [comment]
No I do not expect more trained data from Google. That part of reason why these repositories should be used only for fixing problems (e.g. config files) and not contribution more data from unknown sources.

We have this situation with tesseract 3.x, and quality of user contributed training was questionable and there was decision to split google trained data and contributed data.

There are also other practical topics like for custom trained data it would be nice to have available all training data, documented training steps etc. so somebody could fix possible problems...

**Comment by wincentbalin** [comment]
But the training data is already in [langdata/akk](https://github.com/tesseract-ocr/langdata/) and the training steps are documented in [tesstrain wiki](https://github.com/tesseract-ocr/tesstrain/wiki/Akkadian-Cuneiform), as stated in this pull request's comment.

@zdenop, if you still insist on putting the models for Akkadian into `tessdata_contrib` repository, is it possible to commit models to separate subdirectories, like this:

```
repo
  +--akk
       +--best
       |    +--akk.traineddata
       |
       +--fast
       |    +--akk.traineddata
       |
       +--legacy
            +--akk.traineddata
```

**Pull request closed without merging**
