### PR TITLE
Added OCR-B font trained data

### PR DESCRIPTION
**Pull request by landgenoot**

### CODE REVIEW

**Comment by Shreeshrii** [comment]
```
 combine_tessdata -u ocrb.traineddata ocrb.
Extracting tessdata components from ocrb.traineddata
Wrote ocrb.unicharset
Wrote ocrb.inttemp
Wrote ocrb.pffmtable
Wrote ocrb.normproto
Wrote ocrb.shapetable
1:unicharset:size=3295, offset=168
3:inttemp:size=326252, offset=3463
4:pffmtable:size=358, offset=329715
5:normproto:size=5702, offset=330073
13:shapetable:size=820, offset=335775
```

3.0x version of traineddata

**Comment by stweil** [comment]
Is there also some corresponding data for https://github.com/tesseract-ocr/langdata?

Some more information would be helpful. Did you train a Tesseract 3.x model, or did you train with LSTM? How good is the recognition rate of the new model compared with the available trained data models?

**Comment by stweil** [comment]
Thank you, @Shreeshrii, you answered one of my questions. @landgenoot, maybe you want to add information to https://github.com/tesseract-ocr/tesseract/wiki/Data-Files.

**Comment by amitdo** [comment]
My question is: Do we want to host non-Google tessdata in this repo?

**Comment by zdenop** [comment]
I think non-google data should be separated, because:
- they usually they become unsupported by original author
- there are no input data e.g. only original author can fix possible issues

**Comment by landgenoot** [comment]
No problem. I didn't know this was Google data only.

**Pull request closed without merging**
